table 'Data Dup'
	lineageTag: 0b8b7019-e1cc-4730-a833-8bfb327ec584

	column Column1
		dataType: string
		lineageTag: 399cda4f-4a32-4d18-b486-9f9cf74fc2e0
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 48c0fe64-e72f-48d6-acb5-b6e9d1514853
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: b339473e-ccff-4f1a-b8f2-b64dada9359f
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: a0ee6a94-92b8-4b80-a902-2edd532a902c
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: 7de45bc7-65fc-41f3-86d4-7668533a6741
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	partition 'Data Dup' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Ashik\Downloads\PivotData.xlsx"), null, true),
				    #"Data Dup_Sheet" = Source{[Item="Data Dup",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(#"Data Dup_Sheet",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

